name: Docker Image CI

on:
  [workflow_dispatch]

jobs:

  build:
    if: |
      (github.event_name == 'push' && contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE')) ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t surman2825/guestbook-go:latest

    - name: Publish Docker Image
      run: | 
        docker login -u surman2825 -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
        docker push surman2825/guestbook-go:latest
 
