name: Docker Image CI

on:
  push:
    branches:
      [master]

jobs:

  build:
    if: "contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE') || github.event.pull_request.merged == 'true'"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4s
    - name: Build the Docker image
      run: docker build . -t surman2825/guestbook-go:latest
    - name: Publish Docker Image
      run: |
        docker login -u surman2825 -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
        docker push surman2825/guestbook-go:latest
 