name: Docker Image CI

on:
  [workflow_dispatch]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Printing
        run: echo "${{ toJson(github) }}"

  build:

    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t surman2825/guestbook-go:latest

    - name: Publish Docker Image
      run: | 
        docker login -u surman2825 -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
        docker push surman2825/guestbook-go:latest
 
