name: Docker Image CI

on:
  [workflow_dispatch]

jobs:

  build:
    if: "contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4s
    - name: Build the Docker image
      run: docker build . -t surman2825/guestbook-go:latest
    - name: Publish Docker Image
      run: |
        docker login -u surman2825 -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
        docker push surman2825/guestbook-go:latest
 